/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

float *
sum_1_svc(operands *argp, struct svc_req *rqstp)
{
	static float result;

	result = argp->n1 + argp-> n2;
	printf("Solicitada Adição: %f + %f",argp->n1, argp->n2);
	printf("Resposta enviada: %f", resul);
	return &result;
}

float *
sub_1_svc(operands *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
mul_1_svc(operands *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
div_1_svc(operands *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
abs_1_svc(operands *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
res_1_svc(operands *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
exp_1_svc(operands *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}
