/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
simp_prog_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	operands  sum_1_arg;
	float  *result_2;
	operands  sub_1_arg;
	float  *result_3;
	operands  mul_1_arg;
	float  *result_4;
	operands  div_1_arg;
	float  *result_5;
	operands  abs_1_arg;
	float  *result_6;
	operands  res_1_arg;
	float  *result_7;
	operands  exp_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SIMP_PROG, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sum_1(&sum_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = sub_1(&sub_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = mul_1(&mul_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = div_1(&div_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = abs_1(&abs_1_arg, clnt);
	if (result_5 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = res_1(&res_1_arg, clnt);
	if (result_6 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = exp_1(&exp_1_arg, clnt);
	if (result_7 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host, op;
	float n1, n2;
	CLIENT *clnt;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}


	printf("Calc Distribuidos\n");
	printf("Escolha a operação\n");
	printf("(+)  Adição\n");
	printf("(-) Subtração\n");
	printf("(*) Multiplicação\n");
	printf("(/) Divisão\n");
	printf("(a) Abs\n");
	printf("(r) Resto\n");
	printf("(e) Expoente\n:");
	scanf("%s",&op);
	
	printf("Entre com o número 1\n:");
	scanf("%f",&n1);
	
	printf("Entre com o número2\n:");
	scanf("%f",&n2);

	host = argv[1];
	
	clnt = clnt_create (host, SIMP_PROG, SIMP_VERSION, "udp");

	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit(1);
	}

	simp_prog_1 (host);

	clnt_destroy (clnt);
exit (0);
}
