/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operants {
	int n1;
	int n2;
	char op;
};
typedef struct operants operants;

#define CALC_PROG 0x2ffffff
#define CALC_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define som 1
extern  int * som_1(operants *, CLIENT *);
extern  int * som_1_svc(operants *, struct svc_req *);
#define sub 2
extern  int * sub_1(operants *, CLIENT *);
extern  int * sub_1_svc(operants *, struct svc_req *);
#define mul 3
extern  int * mul_1(operants *, CLIENT *);
extern  int * mul_1_svc(operants *, struct svc_req *);
#define div 4
extern  int * div_1(operants *, CLIENT *);
extern  int * div_1_svc(operants *, struct svc_req *);
#define res 5
extern  int * res_1(operants *, CLIENT *);
extern  int * res_1_svc(operants *, struct svc_req *);
#define abs 6
extern  int * abs_1(operants *, CLIENT *);
extern  int * abs_1_svc(operants *, struct svc_req *);
#define exp 7
extern  int * exp_1(operants *, CLIENT *);
extern  int * exp_1_svc(operants *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define som 1
extern  int * som_1();
extern  int * som_1_svc();
#define sub 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define mul 3
extern  int * mul_1();
extern  int * mul_1_svc();
#define div 4
extern  int * div_1();
extern  int * div_1_svc();
#define res 5
extern  int * res_1();
extern  int * res_1_svc();
#define abs 6
extern  int * abs_1();
extern  int * abs_1_svc();
#define exp 7
extern  int * exp_1();
extern  int * exp_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operants (XDR *, operants*);

#else /* K&R C */
extern bool_t xdr_operants ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
