/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


int
calc_prog_1(char *host, int n1, int n2, char op)
{
	CLIENT *clnt;
	int  *result_1;
	operants  som_1_arg;
	int  *result_2;
	operants  sub_1_arg;
	int  *result_3;
	operants  mul_1_arg;
	int  *result_4;
	operants  div_1_arg;
	int  *result_5;
	operants  res_1_arg;
	int  *result_6;
	operants  abs_1_arg;
	int  *result_7;
	operants  exp_1_arg;


#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if (op == '+') {
		printf("Entrou no MAIS\n");
		som_1_arg.n1 = n1;
		som_1_arg.n2 = n2;
		som_1_arg.op = op;

		result_1 = som_1(&som_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		return *result_1;
	} else if (op == '-') {

		sub_1_arg.n1 = n1;
		sub_1_arg.n2 = n2;
		sub_1_arg.op = op;

		result_2 = sub_1(&sub_1_arg, clnt);
		if (result_2 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		return *result_2;

	} else if (op == '*') {

		mul_1_arg.n1 = n1;
		mul_1_arg.n2 = n2;
		mul_1_arg.op = op;

		result_3 = mul_1(&mul_1_arg, clnt);
		if (result_3 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		return *result_3;

	} else if (op == '/') {

		div_1_arg.n1 = n1;
		div_1_arg.n2 = n2;
		div_1_arg.op = op;

		if (n2 == 0) {
			printf("Não pode dividir por zero\n");
			exit(1);
		} else {
			result_4 = div_1(&div_1_arg, clnt);
			if (result_4 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}
		
		return *result_4;

	} else if (op == 'r') {

		res_1_arg.n1 = n1;
		res_1_arg.n2 = n2;
		res_1_arg.op = op;

		result_5 = res_1(&res_1_arg, clnt);
		if (result_5 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		return *result_5;

	} else if (op == 'a') {

		abs_1_arg.n1 = n1;
		abs_1_arg.n2 = n2;
		abs_1_arg.op = op;

		result_6 = abs_1(&abs_1_arg, clnt);
		if (result_6 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		return *result_6;

	} else if (op == 'e') {

		exp_1_arg.n1 = n1;
		exp_1_arg.n2 = n2;
		exp_1_arg.op = op;

		result_7 = exp_1(&exp_1_arg, clnt);
		if (result_7 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		return *result_7;
	}

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */

}


int
main (int argc, char *argv[])
{
	char *host;
	int n1, n2;
	char op;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	printf("Calc Distribuidos\n");
	printf("Escolha a operação\n");
	printf("(+)  Adição\n");
	printf("(-) Subtração\n");
	printf("(*) Multiplicação\n");
	printf("(/) Divisão\n");
	printf("(a) Abs\n");
	printf("(r) Resto\n");
	printf("(e) Expoente\n:");
	scanf("%s",&op);

	printf("Entre com o número 1\n:");
	scanf("%d",&n1);
	
	printf("Entre com o número 2\n:");
	scanf("%d",&n2);

	host = argv[1];
	printf("Resposta: = %d\n", calc_prog_1 (host, n1, n2, op));

	exit (0);
}
