/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

int *
som_1_svc(operants *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->n1 + argp-> n2;
	printf("Solicitada Adição: %d + %d",argp->n1, argp->n2);
	printf("Resposta enviada: %d", result);

	return &result;
}

int *
sub_1_svc(operants *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->n1 - argp-> n2;
	printf("Solicitada Subtração: %d - %d",argp->n1, argp->n2);
	printf("Resposta enviada: %d", result);

	return &result;
}

int *
mul_1_svc(operants *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->n1 * argp-> n2;
	printf("Solicitada Multiplicação: %d * %d",argp->n1, argp->n2);
	printf("Resposta enviada: %d", result);

	return &result;
}

int *
div_1_svc(operants *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->n1 / argp-> n2;
	printf("Solicitada Divisão: %d / %d",argp->n1, argp->n2);
	printf("Resposta enviada: %d", result);

	return &result;
}

int *
res_1_svc(operants *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->n1 + argp-> n2;
	if(result < 0) result *= -1;
	printf("Solicitada Abs de dois números: |%d + %d|",argp->n1, argp->n2);
	printf("Resposta enviada: %d", result);

	return &result;
}

int *
abs_1_svc(operants *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->n1 % argp->n2;
	printf("Solicitada Resto de dois números: %d res %d", argp->n1, argp->n2);
	printf("Resposta enviada: %d", result);

	return &result;
}

int *
exp_1_svc(operants *argp, struct svc_req *rqstp)
{
	static int  result;

	static int i; 
	result = argp->n1;
	
	for(i = 1; i < argp->n2; i++) {
	  result *= argp->n1;
	}

	printf("Solicitada Expoente de dois números: %d ^ %d",argp->n1, argp->n2);
	printf("Resposta enviada: %d", result);

	return &result;
}
