/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operands {
	float n1;
	float n2;
};
typedef struct operands operands;

#define SIMP_PROG 0x2fffffff
#define SIMP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define sum 1
extern  float * sum_1(operands *, CLIENT *);
extern  float * sum_1_svc(operands *, struct svc_req *);
#define sub 2
extern  float * sub_1(operands *, CLIENT *);
extern  float * sub_1_svc(operands *, struct svc_req *);
#define mul 3
extern  float * mul_1(operands *, CLIENT *);
extern  float * mul_1_svc(operands *, struct svc_req *);
#define div 4
extern  float * div_1(operands *, CLIENT *);
extern  float * div_1_svc(operands *, struct svc_req *);
#define abs 5
extern  float * abs_1(operands *, CLIENT *);
extern  float * abs_1_svc(operands *, struct svc_req *);
#define res 6
extern  float * res_1(operands *, CLIENT *);
extern  float * res_1_svc(operands *, struct svc_req *);
#define exp 7
extern  float * exp_1(operands *, CLIENT *);
extern  float * exp_1_svc(operands *, struct svc_req *);
extern int simp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sum 1
extern  float * sum_1();
extern  float * sum_1_svc();
#define sub 2
extern  float * sub_1();
extern  float * sub_1_svc();
#define mul 3
extern  float * mul_1();
extern  float * mul_1_svc();
#define div 4
extern  float * div_1();
extern  float * div_1_svc();
#define abs 5
extern  float * abs_1();
extern  float * abs_1_svc();
#define res 6
extern  float * res_1();
extern  float * res_1_svc();
#define exp 7
extern  float * exp_1();
extern  float * exp_1_svc();
extern int simp_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operands (XDR *, operands*);

#else /* K&R C */
extern bool_t xdr_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
